package edu.cit.audioscholar.ui.auth

object LegalContent {
    const val TERMS_OF_SERVICE = """
# AudioScholar Terms of Service

**Last Updated:** April 05, 2025

Welcome to AudioScholar! These Terms of Service ("Terms") govern your access to and use of the AudioScholar mobile application and web interface (collectively, the "Service").

By accessing or using the Service, you agree to be bound by these Terms and our Privacy Policy. If you do not agree to these Terms, do not use the Service.

**1. Use of the Service**

* **Eligibility:** AudioScholar is primarily designed for students, particularly those in higher education (college students). By using the Service, you represent and warrant that you are at least 13 years of age. If you are under 18, you must have the permission of a parent or legal guardian to use the Service.
* **License:** We grant you a limited, non-exclusive, non-transferable, revocable license to use the Service for your personal, non-commercial educational purposes, subject to these Terms.
* **Restrictions:** You agree not to:
    * Use the Service for any illegal or unauthorized purpose.
    * Copy, modify, distribute, sell, or lease any part of the Service.
    * Attempt to gain unauthorized access to the Service or its related systems or networks.
    * Interfere with or disrupt the Service or servers or networks connected to the Service.
    * Use any automated system, including robots, spiders, or offline readers, to access the Service in a manner that sends more request messages to our servers than a human can reasonably produce in the same period by using a conventional web browser.
    * Circumvent, disable, or otherwise interfere with security-related features of the Service.
* **Offline Capabilities:** AudioScholar provides offline recording functionality. While you can record offline, AI processing, cloud synchronization, and accessing cloud-stored content require an internet connection. Your use of offline features is still subject to these Terms.
* **Optional PowerPoint Uploads:** You have the option to upload lecture PowerPoint presentations to provide context for AI analysis. You are responsible for ensuring you have the necessary rights to upload and share these presentations.
* **Synchronization:** You can choose between automatic and manual cloud synchronization of your recordings. You are responsible for managing your synchronization settings and understanding the data transfer implications of each option.

**2. Accounts**

* **Account Creation:** You can create an account by logging in with your Google account or GitHub account.
* **Account Responsibilities:** You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
* **User Tiers:** AudioScholar offers different user tiers: Non-Logged-In, Logged-In Free, and Logged-In Premium. The features and limitations of each tier are described on our website and within the application. Your access to certain features (e.g., cloud storage, number of summaries, background recording, recommendation sources) is dependent on your user tier.

**3. Content**

* **Your Content:** You retain all rights to the audio recordings and any optional PowerPoint presentations you upload to the Service.
* **License to Us:** By using the Service and uploading content (including recordings and presentations), you grant us a limited, non-exclusive, royalty-free license to use, store, process, and display your content solely for the purpose of providing and improving the Service to you. This includes transmitting your content to external AI APIs for processing and generating summaries and recommendations.
* **AI-Generated Content:** The summaries and recommendations generated by the Service are based on AI processing of your content. We do not guarantee the accuracy, completeness, or usefulness of AI-generated content. AI-generated content is for informational purposes only and should not be considered a substitute for your own understanding and review of lecture material.
* **Third-Party Content:** The Service may provide recommendations for learning materials from third-party sources (e.g., YouTube, potentially licensed educational content). We are not responsible for the content of these third-party resources. Your access and use of third-party content are subject to the terms and conditions of those third parties.

**4. Fees and Payment**

* **Freemium Model:** AudioScholar operates on a freemium model. Access to certain features is limited for non-logged-in and logged-in free users.
* **Premium Subscriptions:** If you choose to subscribe to a premium account, you agree to pay the applicable subscription fees. Subscription terms and pricing are outlined on our website and within the application.
* **Payment Processing:** Payment for premium subscriptions will be processed through third-party payment processors. We do not store your full payment card details.

**5. External AI APIs**

AudioScholar utilizes external AI APIs, including Google Gemini AI API, for processing your lecture audio and optional presentations. Your content will be shared with these APIs for transcription, summarization, and recommendation generation. The use of these APIs is subject to their respective terms of service and privacy policies. We are not responsible for the actions or omissions of these external AI APIs.

**6. Termination**

We may terminate or suspend your access to the Service at any time, with or without cause, with or without notice, effective immediately.

* **User-Initiated Termination:** You can terminate your account and stop using the Service at any time. Instructions for account deletion can be found within the application settings.
* **Effect of Termination:** Upon termination, your right to use the Service will immediately cease. If you have a paid premium subscription, you may not be entitled to a refund for any unused portion of your subscription.

**7. Disclaimer of Warranties**

THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

**8. Limitation of Liability**

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDIO SCHOLAR, ITS AFFILIATES, DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES.

**9. Indemnification**

You agree to defend, indemnify, and hold harmless AudioScholar and its affiliates, directors, employees, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses.

**10. Governing Law**

These Terms shall be governed and construed in accordance with the laws of [Insert Governing Law Jurisdiction], without regard to its conflict of law provisions.

**11. Changes to These Terms**

We reserve the right, at our sole discretion, to modify or replace these Terms at any time.

**12. Contact Us**

If you have any questions about these Terms, please contact us through the support options available within the AudioScholar application or website.
"""

    const val PRIVACY_POLICY = """
# AudioScholar Privacy Policy

**Last Updated:** April 05, 2025

This Privacy Policy describes how AudioScholar ("we," "us," or "our") collects, uses, and discloses your information when you use our mobile application and web interface (collectively, the "Service").

By using AudioScholar, you agree to the collection and use of information in accordance with this policy.

**1. Information We Collect**

We collect several types of information in connection with your use of the Service:

* **Information You Provide Directly:**
    * **Account Information:** When you log in using Google OAuth 2.0 or GitHub OAuth 2.0, we collect your unique User ID provided by the respective service. We do not collect or store your password for these services.
    * **Lecture Metadata:** Information you provide about your lectures, such as titles or descriptions.
    * **Uploaded Content:** Lecture audio recordings you make using the app and any optional PowerPoint presentations you upload.
    * **User Preferences:** Settings you configure within the app, such as synchronization options.
* **Information Collected Automatically:**
    * **Device Information:** Information about the device you use to access the Service, including device type, operating system, and unique device identifiers.
    * **Usage Data:** Information about how you use the Service, such as the date and time of recordings, features accessed, and interactions within the app and web interface.
    * **Log Data:** Information that your browser sends whenever you visit our web interface, including your IP address, browser type, and access times.
* **Information from External APIs:**
    * **AI Processing Data:** Audio recordings and optional PowerPoint presentations are sent to external AI APIs (specifically, Google Gemini AI API) for processing, transcription, summarization, and recommendation generation. The data processed by these APIs is subject to their own privacy policies.

**2. How We Use Your Information**

We use the information we collect for the following purposes:

* **To provide and maintain the Service:** Including recording and storing your lectures, processing audio, generating summaries, and providing access to your content.
* **To personalize your experience:** Including providing customized recommendations for learning materials.
* **To improve and develop the Service:** We analyze usage data to understand how our Service is used and identify areas for improvement.
* **To manage your account:** Including authenticating users and managing user preferences.
* **To communicate with you:** Including sending you service-related notifications.
* **To ensure the security of the Service:** We use information to detect and prevent fraudulent or unauthorized activity.

**3. Data Storage and Retention**

* **Local Storage:** Recordings are initially stored locally on your device.
* **Cloud Storage (for Logged-In Users with Synchronization Enabled):** Recordings are stored securely in Firebase Storage. Summaries, lecture metadata, user data, and preferences are stored in Firebase Firestore or Realtime Database.
* **Data Retention:** We retain your information for as long as necessary to provide the Service and for legitimate business purposes. You can delete your recordings, summaries, and account data within the application.

**4. Disclosure of Your Information**

We may disclose your information in the following circumstances:

* **To External AI APIs:** We share your audio recordings and optional PowerPoint presentations with external AI APIs (specifically, Google Gemini AI API).
* **With Your Consent:** We may disclose your information with your explicit consent.
* **For Legal Reasons:** We may disclose your information if required to do so by law.
* **To Protect Our Rights:** We may disclose your information to protect our rights, property, or safety.

**5. Offline Capabilities**

AudioScholar offers robust offline capabilities for recording. While recordings are initially stored locally, AI processing, cloud synchronization, and accessing cloud-stored content require an internet connection.

**6. Third-Party Services**

AudioScholar utilizes several third-party services, including Firebase (for database, storage, and authentication), Google OAuth 2.0, GitHub OAuth 2.0, and Google Gemini AI API.

**7. Security**

We take reasonable measures to protect your information from unauthorized access, use, or disclosure. However, no method of transmission over the internet or electronic storage is 100% secure.

**8. Children's Privacy**

AudioScholar is intended for use by students, particularly in higher education (college students). We do not knowingly collect personal information from children under the age of 13.

**9. Changes to This Privacy Policy**

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

**10. Contact Us**

If you have any questions about this Privacy Policy, please contact us through the support options available within the AudioScholar application or website.
"""

    const val HELP_CENTER = """
# AudioScholar Help Center

Welcome to the AudioScholar Help Center! Here you can find answers to common questions and learn how to get the most out of AudioScholar.

## Getting Started

* **What is AudioScholar?**
  AudioScholar is a smart application designed to help students transform lecture audio into actionable insights. It records lectures, uses AI to generate summaries, and provides customized suggestions for related learning materials.
* **How does AudioScholar work?**
  You can record your lectures using the AudioScholar mobile app. The app records the audio, and with an internet connection and synchronization enabled, it can upload the recording to our server. Our server uses AI (specifically, Google Gemini) to process the audio, transcribe it, and generate a summary. You can access your recordings and summaries through both the mobile app and the web interface.
* **What devices can I use AudioScholar on?**
  AudioScholar is available as an Android mobile application and a web interface accessible through a browser on any device.
* **Do I need an internet connection to use AudioScholar?**
  No, you do not need an internet connection to record lectures. AudioScholar has robust offline capabilities, allowing you to record directly on your device. However, an internet connection is required for AI processing, cloud synchronization, accessing cloud storage, and receiving recommendations.
* **How do I sign up for AudioScholar?**
  You can sign up for AudioScholar by logging in with your Google account or GitHub account.

## Recording Lectures

* **How do I start recording a lecture?**
  Open the AudioScholar mobile app and find the recording function. Tap the record button to begin.
* **Can I record a lecture without an internet connection?**
  Yes, you can record lectures offline. The audio will be stored locally on your device.
* **Where are my recordings stored initially?**
  When you record offline, your recordings are stored locally on your device.
* **How do I synchronize my recordings to the cloud?**
  You can manage cloud synchronization in the application settings. You have the option to choose between automatic or manual synchronization. Automatic synchronization will upload your recordings to the cloud when an internet connection is available and the app is running. Manual synchronization requires you to explicitly trigger the upload.
* **What happens if I lose internet connection during a recording?**
  If you lose internet connection while recording, the recording will continue to be stored locally on your device. Cloud synchronization will pause until a connection is re-established and, if enabled, triggered.
* **Can I record in the background?**
  Background recording is available for **Logged-In Premium Users** only. If you are a non-logged-in user or a logged-in free user, the recording will automatically pause if you switch apps or lock the screen.
* **How do I pause or stop a recording?**
  Use the pause and stop buttons within the mobile application's recording interface.
* **Can I provide lecture PowerPoint presentations?**
  Yes, AudioScholar optionally allows you to upload lecture PowerPoint presentations. This can significantly improve the quality of the AI analysis and summarization process by providing valuable context. Look for the option to upload presentations associated with a lecture within the app.

## Summaries and Recommendations

* **How are summaries generated?**
  Once your recording is synchronized to the cloud and processed, AudioScholar uses external AI APIs (specifically, Google Gemini) to transcribe the audio and generate a concise summary of the lecture content.
* **Can I view summaries offline?**
  If the summary has been generated and synchronized to your device while you had an internet connection, you may be able to view it offline. However, initial processing and generation require an internet connection.
* **How many summaries can I have?**
  The number of active summaries you can have depends on your user tier:
    * **Non-Logged-In Users:** Limited to **one active summary** at a time. You must delete the existing summary to create a new one.
    * **Logged-In Free Users:** Can generate up to **three active summaries** at a time.
    * **Logged-In Premium Users:** Have **unlimited summaries**.
* **What are recommendations?**
  AudioScholar provides recommendations for related learning materials to help you further understand the lecture topics.
* **Where do the recommendations come from?**
  The source of recommendations varies based on your user tier:
    * **Non-Logged-In Users:** No access to the recommendation engine.
    * **Logged-In Free Users:** Recommendations are limited to **YouTube** as the source.
    * **Logged-In Premium Users:** Recommendations are drawn from an **expanded range of learning resources** beyond YouTube.
* **How can I improve the accuracy of summaries and recommendations?**
  Providing associated lecture PowerPoint presentations can significantly improve the accuracy of the AI analysis and the relevance of recommendations.

## Account and Data

* **How do I log in?**
  You can log in using your Google account or GitHub account.
* **What is the difference between non-logged-in, logged-in free, and logged-in premium users?**
  These tiers offer different levels of access to features:
    * **Non-Logged-In Users:** Local storage only, single summary limit, no account features, no recommendations.
    * **Logged-In Free Users:** Limited cloud access and synchronization, three summary limit, background recording disabled, limited YouTube-only recommendations.
    * **Logged-In Premium Users:** Unlimited cloud access and synchronization, unlimited summaries, background recording enabled, expanded recommendations.
* **Where is my data stored?**
  Your recordings and summaries are stored locally on your device. If you are a logged-in user with cloud synchronization enabled, they are also stored securely in Firebase Storage in the cloud. User data, lecture metadata, summaries, and preferences are stored in Firebase Firestore or Realtime Database.
* **How secure is my data?**
  We use industry-standard security measures to protect your data. Cloud storage and user authentication are handled through secure Firebase services.
* **Can I delete my data?**
  Yes, you can delete your recordings, summaries, and account data within the application. Refer to the application's settings or account management section.
* **What is the difference between automatic and manual synchronization?**
  Automatic synchronization will upload your recordings to the cloud automatically when an internet connection is available and the app is running. Manual synchronization requires you to explicitly initiate the upload process within the app.

## Troubleshooting

* **My recording stopped unexpectedly.**
  Check if you are a non-logged-in or logged-in free user. Background recording is disabled for these tiers and will pause if you switch apps or lock the screen. For premium users, ensure you have a stable internet connection if synchronization is enabled, though offline recording should continue.
* **My summary is not generating.**
  Ensure you have an active internet connection and that your recording has been successfully synchronized to the cloud (if you are a logged-in user). AI processing requires an internet connection.
* **I am unable to log in with Google/GitHub.**
  Ensure you have a stable internet connection and that you are providing the correct credentials. Check the permissions requested by the OAuth process.
* **I have reached my summary limit.**
  If you are a non-logged-in user, you must delete your existing summary to create a new one. If you are a logged-in free user, you can delete existing summaries to stay within your limit of three active summaries, or consider upgrading to a premium account for unlimited summaries.

## Contact Us

If you have any other questions or need further assistance, please contact us through the support options available within the AudioScholar application or website.
"""
}